language: minimal
dist: xenial
install: ./install-dependencies.sh
script: ./typecheck-all.sh

jobs:
  include:
    - script: ./RELEASE/CI/typecheck-all.sh.1
    - script: ./RELEASE/CI/typecheck-all.sh.2
    - script: ./RELEASE/CI/typecheck-all.sh.3
    - script: ./RELEASE/CI/typecheck-all.sh.4
