language: minimal
dist: xenial
install: ./install-dependencies.sh
script: ./typecheck-all.sh

jobs:
  include:
    - script: ./typecheck-all.sh nasalib.all.1
    - script: ./typecheck-all.sh nasalib.all.2
